### ISSUE TITLE
messages present when ts is locked

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#3135]
Today I got two messages from a friend while ts was unable to open (because of the "fuck*ng commas"). They never appeared in the conversation list, and now they are shown jn the notification area every time I lock ts
Debug log https://gist.github.com/f34eca0e5ac393d836cc

**Comment by volcano99** [comment]
I know there was a similar bug a while ago, but I also know it had been fixed. Which is why I'm reporting it here

**Comment by moxie0** [comment]
should be resolved now, but you'll have to reinstall to clear those messages

**Comment by volcano99** [comment]
What exactly do you mean by "resolved"? I used to have the problem before like 2.13, and it got fixed with an update. After that, no more messages when ts locked.
And then yesterday it happened again with two new messages. If "resolved" means that the users have to reinstall to clear those messages every time it happens, then it is not resolved, at all.  Also because I had to clear the data and that means losing all your messages... of course I did a plaintext backup, but you know very well how many issues related to group chats and photos there are... So no, if you expect the users to regularly reinstall the app, this issue has not been resolved.

**Comment by moxie0** [comment]
Please stop running the beta.

**Comment by Mihahn** [comment]
I experience the same problem since the comma bug. Is the only solution reinstalling the app?
