### ISSUE TITLE
contacts with multiple accounts attached apear twice

### ISSUE THREAD

**Issue by xmatthias** [WhisperSystems/TextSecure#4029]
After enabling "send sms with textsecure" i tried to select a contact to send the sms to.
Here i noticed that many contacts were appearing twice (or more even more often) which was not the case in the "original" contact app. They only appear twice in the "all contacts"-section, textsecure contacts are only once there.

This appears to be related to the count of numbers attached to a contact - having the mobile number + that contact as whatsapp-contact with the same number has the contact appear twice (with the same number) - if that contact is also on facebook (or has 2 numbers) that contact appears 4 times.

phone: oneplus one, stock 5.0.2 android (as delivered by oneplus), official textsecure app from the appstore (reinstalled today) (2.25.3).

**Comment by Dyras** [comment]
Are they appearing with the same number, or with a different number? My dad has two numbers and he appears twice.

**Comment by yzrmn** [comment]
I had the same problem a couple of days ago (2.25.3).
The numbers were the same but displayed differently (+0123 456 789 and +0123456789).

**Comment by xmatthias** [comment]
the numbers are exactly the same (ppl with 2 numbers show 4 times)

also - it should be noted that this doesn't happen with one or 2 contacts, but with almost all.

**Comment by AlfonsoMuskedunder** [comment]
Interesting. Since a couple of days nearly all of my TextSecure-using contacts are Listed twice. (Only two new ones I have added since appear once.) Their respective numbers are identical.

All other contacts are listed once.

**Comment by xmatthias** [comment]
to clarify: 
i see the following:
```
textsecure users:
    john (number a)
    jack (number b)
all contacts:
    john (number a)
    john (number a)
    jack (number b)
    jack (number b)
    ralf (number c)
    ralf (number c)
    ralf (number d)
    ralf (number d)
    jane (number e)
    jane (number e)
    ...
```

for ralf, i have 2 numbers saved, so i can understand seeing him twice - however, john, jane and jack appear twice under all contacts even if it's the same number (no whitespace or other difference).

only thing i did notice when looking at the default contacts-app is that there i see them as contact (google) and contact (whatsapp), so probably that's what's confusing the app. 

However this appears for almost every contact (as there are only very few contacts with only one contact info (almost all use whatsapp as well)).

i've just registered for the beta-program so maybe the fix is already there - if not i'll try to compile and install from source to see if that helps.

**Comment by dcherian** [comment]
Same issue on 2.26.4. I also think that it has to do with the number being registered with other services -- WhatsApp registered numbers are duplicates in the list.

**Comment by AlfonsoMuskedunder** [comment]
My case is a bit different. I see:
```
TextSecure users:
    john (number a)
    john (number a)
    jack (number b)
    jack (number b)
    ralf (number c)
All users:
    john (number a)
    jack (number b)
    ralf (number c)
    jane (number d),
```
where "ralf" was added to my phone's contacts only recently.

The double listing of TextSecure users is independent of whether they have affiliations with any other accounts; some do, some don't. However, when I view a contact in my native contacts app (my OS is a derivative of Android 4.2.2; no contact is stored on the phone or the SIM card; all contacts are stored via CalDAV), there is a section with connections to other accounts, and in case of each doubly listed TS user TextSecure itself is listed twice (with completely identical phone numbers).

**Comment by xmatthias** [comment]
I fixed this issue myself with #4069.

**Comment by riyapenn** [comment]
Related fix to https://github.com/WhisperSystems/TextSecure/issues/1946

**Comment by xmatthias** [comment]
@riyapenn unfortunately no - the fix only eliminates true duplicates - numbers with spaces and without spaces are not seen as duplicates automatically so that's not working.
Only solution that comes to my mind would be to scan the whole tree and eliminate spaces - however that's the worst option here.
Better fix your adress-book (i did the same once this fix worked). it's less work than it looks ;)

**Comment by oaim** [comment]
This is still a problem on my Android 4.1.2. I'm using TS 2.28.0

**Comment by xmatthias** [comment]
yes, sure - the api-call it uses was introduced in andriod lollipop -> android 5.0 and up
sry :)
